server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: ASC
    operations-sorter: method
    info:
      title: Reservas API
      version: v1.0.0
      description: API para gerenciamento de reservas, locações e clientes.
    servers:
      - url: http://localhost:8080

jwt:
  secret-key: cdcbe42a8d697568a59297eaa62fb60da018dfb0ef2716b45637fd24736097d5
  expiration-ms: 86400000