server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: cdcbe42a8d697568a59297eaa62fb60da018dfb0ef2716b45637fd24736097d5
  expiration-ms: 86400000